name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # Run node tests
  test-node:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Build should be up to date
        run: |
          git diff --exit-code || (echo "There were changes in the build output - please commit build" && exit 1)

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.15.7
      - name: Run Tests
        run: pnpm test

      - name: Check Format
        run: pnpm prettier -c .

  # Run the action on itself on multiple OSes
  run-self:
    strategy:
      fail-fast: false
      matrix:
      os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      SCCACHE_GHA_ENABLED: 'true'
      RUSTC_WRAPPER: 'sccache'
    steps: # Setup
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Run Self as Action
        uses: ./ # Uses the action in the current repo
        with:
          project: './__tests__/test-cargo-repo'
          run: 'test,clippy,fmt,doc,shear,deny'
          flow-fmt-toolchain: 'nightly'
